apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  {{- if ne .Values.volume.storageClass "" }}
  storageClassName: {{ .Values.volume.storageClass }}
  {{- end }}
  volumeMode: Filesystem